### PR TITLE
docs(components): [rate] update docs

### PR DESCRIPTION
**Pull request by badspider7**
update rate docs and update docs/vuesax-alpha@0.2.0-beta.75

### CODE REVIEW

**Comment by badspider7** [comment]
some error occurs in pnpm-lock.yaml,should i remove it?

**Comment by tranthinh-coding** [comment]
Sorry I didn't notice the announcement, I will look this bug

**Comment by tranthinh-coding** [comment]
> some error occurs in pnpm-lock.yaml,should i remove it?

Is there any way to handle that error?

**Comment by badspider7** [comment]
yes, i will fix as soon

**Pull request merged**
